### ISSUE TITLE
Unable to run using python-lua

### ISSUE THREAD

**Issue by notzoom** [NeonMercury/python-lua#3]
I have installed it with success but my system does not recognize the command python-lua. 

I am on Ubuntu.

This is a very useful project, eager to use it.

Thanks a lot !

**Comment by NeonMercury** [comment]
Hello.
I am sorry for some misunderstanding, it is not installing like a python module to run it directly.
To run python-lua you need to execute it via python with the following command: `python python-lua [-h] [--show-ast] [--only-lua-init] [--no-lua-init] [IF]`
