### ISSUE TITLE
Did you ever have decent programming lessons before releasing this rubbish?

### ISSUE THREAD

**Issue by Ikkeme** [NeonMercury/python-lua#4]
You can't convert python to lua by inserting the keyword "local" in front of each line of code.

Try to convert this one and you'll see:
https://github.com/Broham/suncalcPy/blob/master/suncalc.py

Good free advice from me: delete this project, take a decent programming course and then try again.

**Comment by NeonMercury** [comment]
Why so serious? Why so toxic?
You can't convert one language to another. And it is doesn't matter, you are converting spanish to english or python to lua. There always will be many limitations.

Who are you to listen your free advices? No projects, no repos. It's an open source. Don't give an advice, fork and give a code.
